#!/usr/bin/env python3
"""Import unchanged, hash-verified visual assets from the fixed PassionWave source.

No image transformation, generator, network access or customer configuration.
"""
from pathlib import Path
import argparse
import hashlib
import json
import subprocess

parser=argparse.ArgumentParser()
parser.add_argument("upstream", type=Path)
args=parser.parse_args()
commit="9cc5576c2fd4a9beb56cad24e211957c43aa2c62"
actual=subprocess.check_output(["git","-C",str(args.upstream),"rev-parse","HEAD"],text=True).strip()
if actual!=commit: raise SystemExit("Upstream commit differs; explicit source review required")
root=Path(__file__).resolve().parent
def source_bytes(path):
    return subprocess.check_output(["git","-C",str(args.upstream),"show",f"{commit}:{path}"])
avatar_manifest=source_bytes("assets/weather-avatar/manifest.json")
manifest=json.loads(avatar_manifest)
items=[]
for item in sorted(manifest["images"],key=lambda x:x["index"]):
    items.append((item["index"],"avatar/"+item["key"],"assets/weather-avatar/"+item["file"],item["sha256"]))
assert [r[0] for r in items]==list(range(52))
tree=subprocess.check_output(["git","-C",str(args.upstream),"ls-tree","-r","--name-only",commit,
                              "--","assets/screensaver/states"],text=True)
photos=sorted(Path(path) for path in tree.splitlines() if path.endswith(".jpg"))
assert len(photos)==15
photo_hashes={line.split()[1].lstrip('*'):line.split()[0] for line in
              source_bytes("assets/screensaver/states/SHA256SUMS").decode().splitlines() if line.strip()}
for i,p in enumerate(photos):
    items.append((52+i,"weather/"+p.stem,str(p),photo_hashes[p.name]))
unique={};records=[]
for index,name,source,expected in items:
    # Read directly from the Git object to avoid accidental changes in the local tree.
    data=source_bytes(source)
    sha=hashlib.sha256(data).hexdigest()
    if sha!=expected:raise SystemExit("Hash differs: "+source)
    filename="a_"+sha+".jpg"
    (root/"assets"/filename).write_bytes(data)
    unique[filename]=len(data)
    records.append(dict(index=index,name=name,source=source,sha256=sha,bytes=len(data),file="assets/"+filename,width=368,height=368))
(root/"manifest.json").write_text(json.dumps(dict(schema_version=1,upstream_commit=commit,images=records,unique_images=len(unique),embedded_unique_bytes=sum(unique.values()),decoded_double_buffer_bytes=368*368*2*2),indent=2)+"\n")
(root/"UPSTREAM-LICENSE.txt").write_bytes(source_bytes("LICENSE"))
(root/"upstream-avatar-manifest.json").write_bytes(avatar_manifest)
provenance=source_bytes("assets/screensaver/README.md").decode()
provenance=provenance.replace(
    "[`states/`](states/)",
    f"[`states/`](https://github.com/passion-wave/Passion-Wave-rotaryknob/tree/{commit}/assets/screensaver/states)")
(root/"upstream-weather-provenance.md").write_text(provenance)
lines=["// Generated by import_assets.py; JPEG content remains unchanged.","// SPDX-License-Identifier: MIT",'#include "pw_assets_internal.h"']
for name in sorted(unique):
    symbol=name.replace('.','_')
    lines.append(f'extern const uint8_t _binary_{symbol}_start[];')
lines.append("const pw_asset_source_t pw_asset_sources[PW_ASSET_COUNT] = {")
for r in records:
    sym=Path(r['file']).name.replace('.','_')
    lines.append(f'    {{"{r["name"]}", _binary_{sym}_start, {r["bytes"]}}},')
lines.append("};\n")
(root/"pw_assets_index.c").write_text('\n'.join(lines))
(root/"assets.cmake").write_text('set(PW_ASSET_FILES\n'+''.join(f'    "assets/{name}"\n' for name in sorted(unique))+')\n')
print(f'{len(records)} keys; {len(unique)} unique JPEGs; {sum(unique.values())} compressed bytes')
