// Generated by import_assets.py; JPEG content remains unchanged.
// SPDX-License-Identifier: MIT
#include "pw_assets_internal.h"
extern const uint8_t _binary_a_02a0768acdae5f06cd7b98309e52ceca3e8c4281c2547ea4e6e0dbea6724eca4_jpg_start[];
extern const uint8_t _binary_a_07c2fddff55a8f1d753287517cec77829fa9b5e14d290521214cc5d358afa0f4_jpg_start[];
extern const uint8_t _binary_a_09a67bbf64011e23af23aaa4c8183aec0578c86491a268b673e31ded4d0b7e6f_jpg_start[];
extern const uint8_t _binary_a_0d53746f1f35d7fb696963e186d37daf3f1a469eea008afd74cb3e04c48a847a_jpg_start[];
extern const uint8_t _binary_a_14f0a0ce495464abb26f74aa759d7c705697667539acd19602f3d47b08899f0b_jpg_start[];
extern const uint8_t _binary_a_18d4f45cd16967bb2ae98a28ce069b28df76555069c718977197f841291b1ac4_jpg_start[];
extern const uint8_t _binary_a_19149b11d90504c9f2531ee22c2ebc25f067a4a821e0571217987e33c985afc7_jpg_start[];
extern const uint8_t _binary_a_1c536fe43e5999bfee776d1b1f841fa3e8bf502e2f6c032aa078752aa51e2abc_jpg_start[];
extern const uint8_t _binary_a_1dd1d3a6fd84dd558f57e5712b3f7ecec014e0573f7158bf23df6ad4d1902f5f_jpg_start[];
extern const uint8_t _binary_a_1ed94e8bd41b8fc9593709b0cce23f8fba26faae93cb38bb949f04772135bc26_jpg_start[];
extern const uint8_t _binary_a_2a40e7d0492e39b854886a057c8d1f5d1e915fdcebe7f55d90e6931275407146_jpg_start[];
extern const uint8_t _binary_a_34cd0f4875723447bd93ec6b5b119876c65df54ab07f7197d0d4035f834ab209_jpg_start[];
extern const uint8_t _binary_a_34e292f30e1202b8795f1267e1b4495b1714388a86a6a1f29bb56bef822d8a70_jpg_start[];
extern const uint8_t _binary_a_36bf38be3130d0260fc95d04951a0036320a6f6eb56a6d27f450b58a31f16090_jpg_start[];
extern const uint8_t _binary_a_3c2ae47017c0c9568b83bb14b2adbe3ba4c1f94e43946b62e23115d9fa16e8bb_jpg_start[];
extern const uint8_t _binary_a_421c28f5bd61fefd9f370accaa85829eb5fa5afc4eb1f7883253e73fe982f81d_jpg_start[];
extern const uint8_t _binary_a_4425e66040cac2963fe54c0bf7b27a11798240e75464ead05221d27ab448d8db_jpg_start[];
extern const uint8_t _binary_a_52f44be5123809e3f5732f7d87718d898bbb6418f6edb89d53eeb87955a9b8b4_jpg_start[];
extern const uint8_t _binary_a_53e376b19b21436ae0c1d1e53324c89ee0368b9e2dee8c88c062ab065f6c2e13_jpg_start[];
extern const uint8_t _binary_a_557b0645b67c817c2a95e6a212aa38fdbf1cf57c6f9b0550e995aa638aeeb4b4_jpg_start[];
extern const uint8_t _binary_a_5856a238002f818c928c9d2706bfbded9ad173d74cd6733af42fe3f0a0a8add1_jpg_start[];
extern const uint8_t _binary_a_5da7c36d992475c8ac2fa3a88cfe93a09ada74475aa983ebcb74f63a3760ab78_jpg_start[];
extern const uint8_t _binary_a_5e029359eada5cf7d7d5e1cbc6aa5c29f6e3ea1252344b9e237617d97b22181e_jpg_start[];
extern const uint8_t _binary_a_6157d31c358ab9ce6f187163b4b5d3ba3c23aa751c0ef58917d97a77773a68a9_jpg_start[];
extern const uint8_t _binary_a_69a40ad5dd4fe8384c5010203b6cb1eda780573a053737230d0664f9f1013ff7_jpg_start[];
extern const uint8_t _binary_a_6b037622a16b899c9b5428ac7a387454b26daa09ce1cd6b38b35b41b6a5cdaf7_jpg_start[];
extern const uint8_t _binary_a_6b60e1cb6581372e5b7b5be7256b4580a1802a80ece56e7813726e2d88c47ccd_jpg_start[];
extern const uint8_t _binary_a_711c76868cdcd82029e0ac86af747dc029f0062b5ceac5a1fc2b33817b354ade_jpg_start[];
extern const uint8_t _binary_a_771f490cb1c5d9762ca0c83bbec5f8a19e5e2da348b7a5c2bd4b6032c8cb7038_jpg_start[];
extern const uint8_t _binary_a_7cf482cef766d06ae57125c5abfa3e702ff297fd03bfbd71524d3cf94d623a63_jpg_start[];
extern const uint8_t _binary_a_8614c214a1c40fb0f8aa66d654205f6b4e54195c49efb7ab9b15999cf2246e0e_jpg_start[];
extern const uint8_t _binary_a_86d6bded2044c8aa0c7f8183f4b213f157336b84ce51d3184cfc380b5d75ff3b_jpg_start[];
extern const uint8_t _binary_a_89eac31281e5084aa5c771a952e14b31406622687e72300f130039e408eac335_jpg_start[];
extern const uint8_t _binary_a_8cc46e1de425a42d94477c32169e2b691e3da837838599e6a73b7e110f0f4b90_jpg_start[];
extern const uint8_t _binary_a_90a399a23ca90adc543de924d96aced1108e09d0cba80332717340953bddde09_jpg_start[];
extern const uint8_t _binary_a_9140d3b5f96f7d89d4dd8e35618e5242ffd663f96a9a61b6ca2d644ce6da62c3_jpg_start[];
extern const uint8_t _binary_a_91b6b93a61996d3c44eca47178d1960586577bf0bd65418b66de24e872dd0ef1_jpg_start[];
extern const uint8_t _binary_a_928e45f22d06cc9eace269b19e3dc2ba9dc69d0fec9d594d2a9522c34ab75021_jpg_start[];
extern const uint8_t _binary_a_995b257794d77374b3487eb99db66aaeaaed865b4fa9b941e421663998560678_jpg_start[];
extern const uint8_t _binary_a_a6d0f8b24a84bf0dee313595eb3b9782652f6b29cc026428e4f5ef7f09c51edf_jpg_start[];
extern const uint8_t _binary_a_b15c94df3dda8f8540023f9cb8b70351e2eca0bfd8b1e855e0c7c99b5f63a937_jpg_start[];
extern const uint8_t _binary_a_b30086592873cd2fd36638853ce95be1343ca575e61e6a0327f54cf75d189d6f_jpg_start[];
extern const uint8_t _binary_a_bd8745289e1da57e4aad3c5dadb1fc31c616f7d8c4c39af42cd46fd3bf38891d_jpg_start[];
extern const uint8_t _binary_a_cc7f857ca5cacf68ded3b8f1dfc36be9af5b22c4a0b4603cda84af8f43972133_jpg_start[];
extern const uint8_t _binary_a_d4bb92b37b286b7b3ee0d3ec3b2632b2ccdaf8d4a0cdeee55e64665abbd5200e_jpg_start[];
extern const uint8_t _binary_a_d69cbacea29f5b9917f60fd8d2078b4ba5da85755c88c82e0ad489dd899709bf_jpg_start[];
extern const uint8_t _binary_a_db0cf2dc5c7f45c449c46caee8e8b238a7a7a62bdc38b82e9c5de0a1d1d1b79c_jpg_start[];
extern const uint8_t _binary_a_e1a53458b47bce9c954f6686473314f372685baf0e91bc065c22bcd4f23362d4_jpg_start[];
extern const uint8_t _binary_a_e50f238f142ceaf15e6cb47ce1c3f9286324f46af8dc768ef6e4870810c2c412_jpg_start[];
extern const uint8_t _binary_a_e66c2c7bd4ed7d99812a465c31f73403149811254f0444789b60e02990585cf3_jpg_start[];
extern const uint8_t _binary_a_e83dad5abeee8cfe53830542abbc9546f6b185c13dd287e8a18d35cba1dd3a87_jpg_start[];
extern const uint8_t _binary_a_e8498de3c81d3c2e586f166a87c83da5ae87d47e40d0b5f5004dd6c6fd305f36_jpg_start[];
extern const uint8_t _binary_a_e9d0fd48b8d50fe4d5d949d2639e04afcfe6a0641b79e1f0a32236129e8e037c_jpg_start[];
extern const uint8_t _binary_a_ecb0b9cb252942cb6eb5853fc1db2f178fe82ef1ba5d855a64fc89b6a3a8ce5d_jpg_start[];
extern const uint8_t _binary_a_f66cdeb3d47bf385a591749fe60f6e0b2ed76661e0d64011603c026a3bbb1d88_jpg_start[];
const pw_asset_source_t pw_asset_sources[PW_ASSET_COUNT] = {
    {"avatar/brown_brown/hot-dry", _binary_a_421c28f5bd61fefd9f370accaa85829eb5fa5afc4eb1f7883253e73fe982f81d_jpg_start, 13823},
    {"avatar/brown_brown/warm-dry", _binary_a_36bf38be3130d0260fc95d04951a0036320a6f6eb56a6d27f450b58a31f16090_jpg_start, 13885},
    {"avatar/brown_brown/mild-dry", _binary_a_9140d3b5f96f7d89d4dd8e35618e5242ffd663f96a9a61b6ca2d644ce6da62c3_jpg_start, 13614},
    {"avatar/brown_brown/cool-dry", _binary_a_1c536fe43e5999bfee776d1b1f841fa3e8bf502e2f6c032aa078752aa51e2abc_jpg_start, 14329},
    {"avatar/brown_brown/cold-dry", _binary_a_928e45f22d06cc9eace269b19e3dc2ba9dc69d0fec9d594d2a9522c34ab75021_jpg_start, 13037},
    {"avatar/brown_brown/frost-dry", _binary_a_18d4f45cd16967bb2ae98a28ce069b28df76555069c718977197f841291b1ac4_jpg_start, 13085},
    {"avatar/blond_hazel/hot-dry", _binary_a_5e029359eada5cf7d7d5e1cbc6aa5c29f6e3ea1252344b9e237617d97b22181e_jpg_start, 13954},
    {"avatar/blond_hazel/warm-dry", _binary_a_02a0768acdae5f06cd7b98309e52ceca3e8c4281c2547ea4e6e0dbea6724eca4_jpg_start, 13903},
    {"avatar/blond_hazel/mild-dry", _binary_a_52f44be5123809e3f5732f7d87718d898bbb6418f6edb89d53eeb87955a9b8b4_jpg_start, 13788},
    {"avatar/blond_hazel/cool-dry", _binary_a_1dd1d3a6fd84dd558f57e5712b3f7ecec014e0573f7158bf23df6ad4d1902f5f_jpg_start, 14468},
    {"avatar/blond_hazel/cold-dry", _binary_a_6b037622a16b899c9b5428ac7a387454b26daa09ce1cd6b38b35b41b6a5cdaf7_jpg_start, 12995},
    {"avatar/blond_hazel/frost-dry", _binary_a_5856a238002f818c928c9d2706bfbded9ad173d74cd6733af42fe3f0a0a8add1_jpg_start, 12986},
    {"avatar/brown_brown/hot-wind", _binary_a_a6d0f8b24a84bf0dee313595eb3b9782652f6b29cc026428e4f5ef7f09c51edf_jpg_start, 13235},
    {"avatar/brown_brown/warm-wind", _binary_a_a6d0f8b24a84bf0dee313595eb3b9782652f6b29cc026428e4f5ef7f09c51edf_jpg_start, 13235},
    {"avatar/brown_brown/mild-wind", _binary_a_4425e66040cac2963fe54c0bf7b27a11798240e75464ead05221d27ab448d8db_jpg_start, 13183},
    {"avatar/brown_brown/cool-wind", _binary_a_1ed94e8bd41b8fc9593709b0cce23f8fba26faae93cb38bb949f04772135bc26_jpg_start, 13694},
    {"avatar/brown_brown/cold-wind", _binary_a_928e45f22d06cc9eace269b19e3dc2ba9dc69d0fec9d594d2a9522c34ab75021_jpg_start, 13037},
    {"avatar/brown_brown/frost-wind", _binary_a_18d4f45cd16967bb2ae98a28ce069b28df76555069c718977197f841291b1ac4_jpg_start, 13085},
    {"avatar/blond_hazel/hot-wind", _binary_a_34cd0f4875723447bd93ec6b5b119876c65df54ab07f7197d0d4035f834ab209_jpg_start, 13334},
    {"avatar/blond_hazel/warm-wind", _binary_a_34cd0f4875723447bd93ec6b5b119876c65df54ab07f7197d0d4035f834ab209_jpg_start, 13334},
    {"avatar/blond_hazel/mild-wind", _binary_a_711c76868cdcd82029e0ac86af747dc029f0062b5ceac5a1fc2b33817b354ade_jpg_start, 13273},
    {"avatar/blond_hazel/cool-wind", _binary_a_b30086592873cd2fd36638853ce95be1343ca575e61e6a0327f54cf75d189d6f_jpg_start, 13832},
    {"avatar/blond_hazel/cold-wind", _binary_a_6b037622a16b899c9b5428ac7a387454b26daa09ce1cd6b38b35b41b6a5cdaf7_jpg_start, 12995},
    {"avatar/blond_hazel/frost-wind", _binary_a_5856a238002f818c928c9d2706bfbded9ad173d74cd6733af42fe3f0a0a8add1_jpg_start, 12986},
    {"avatar/brown_brown/hot-wet", _binary_a_8cc46e1de425a42d94477c32169e2b691e3da837838599e6a73b7e110f0f4b90_jpg_start, 13947},
    {"avatar/brown_brown/warm-wet", _binary_a_69a40ad5dd4fe8384c5010203b6cb1eda780573a053737230d0664f9f1013ff7_jpg_start, 14198},
    {"avatar/brown_brown/mild-wet", _binary_a_ecb0b9cb252942cb6eb5853fc1db2f178fe82ef1ba5d855a64fc89b6a3a8ce5d_jpg_start, 14248},
    {"avatar/brown_brown/cool-wet", _binary_a_b15c94df3dda8f8540023f9cb8b70351e2eca0bfd8b1e855e0c7c99b5f63a937_jpg_start, 13579},
    {"avatar/brown_brown/cold-wet", _binary_a_e83dad5abeee8cfe53830542abbc9546f6b185c13dd287e8a18d35cba1dd3a87_jpg_start, 12576},
    {"avatar/brown_brown/frost-wet", _binary_a_5da7c36d992475c8ac2fa3a88cfe93a09ada74475aa983ebcb74f63a3760ab78_jpg_start, 12308},
    {"avatar/blond_hazel/hot-wet", _binary_a_e1a53458b47bce9c954f6686473314f372685baf0e91bc065c22bcd4f23362d4_jpg_start, 14019},
    {"avatar/blond_hazel/warm-wet", _binary_a_09a67bbf64011e23af23aaa4c8183aec0578c86491a268b673e31ded4d0b7e6f_jpg_start, 14184},
    {"avatar/blond_hazel/mild-wet", _binary_a_19149b11d90504c9f2531ee22c2ebc25f067a4a821e0571217987e33c985afc7_jpg_start, 14210},
    {"avatar/blond_hazel/cool-wet", _binary_a_f66cdeb3d47bf385a591749fe60f6e0b2ed76661e0d64011603c026a3bbb1d88_jpg_start, 13639},
    {"avatar/blond_hazel/cold-wet", _binary_a_e8498de3c81d3c2e586f166a87c83da5ae87d47e40d0b5f5004dd6c6fd305f36_jpg_start, 12732},
    {"avatar/blond_hazel/frost-wet", _binary_a_e50f238f142ceaf15e6cb47ce1c3f9286324f46af8dc768ef6e4870810c2c412_jpg_start, 12404},
    {"avatar/brown_brown/hot-snow", _binary_a_8cc46e1de425a42d94477c32169e2b691e3da837838599e6a73b7e110f0f4b90_jpg_start, 13947},
    {"avatar/brown_brown/warm-snow", _binary_a_69a40ad5dd4fe8384c5010203b6cb1eda780573a053737230d0664f9f1013ff7_jpg_start, 14198},
    {"avatar/brown_brown/mild-snow", _binary_a_07c2fddff55a8f1d753287517cec77829fa9b5e14d290521214cc5d358afa0f4_jpg_start, 14999},
    {"avatar/brown_brown/cool-snow", _binary_a_8614c214a1c40fb0f8aa66d654205f6b4e54195c49efb7ab9b15999cf2246e0e_jpg_start, 14830},
    {"avatar/brown_brown/cold-snow", _binary_a_90a399a23ca90adc543de924d96aced1108e09d0cba80332717340953bddde09_jpg_start, 13527},
    {"avatar/brown_brown/frost-snow", _binary_a_34e292f30e1202b8795f1267e1b4495b1714388a86a6a1f29bb56bef822d8a70_jpg_start, 13390},
    {"avatar/blond_hazel/hot-snow", _binary_a_e1a53458b47bce9c954f6686473314f372685baf0e91bc065c22bcd4f23362d4_jpg_start, 14019},
    {"avatar/blond_hazel/warm-snow", _binary_a_09a67bbf64011e23af23aaa4c8183aec0578c86491a268b673e31ded4d0b7e6f_jpg_start, 14184},
    {"avatar/blond_hazel/mild-snow", _binary_a_e66c2c7bd4ed7d99812a465c31f73403149811254f0444789b60e02990585cf3_jpg_start, 15180},
    {"avatar/blond_hazel/cool-snow", _binary_a_6b60e1cb6581372e5b7b5be7256b4580a1802a80ece56e7813726e2d88c47ccd_jpg_start, 14953},
    {"avatar/blond_hazel/cold-snow", _binary_a_e9d0fd48b8d50fe4d5d949d2639e04afcfe6a0641b79e1f0a32236129e8e037c_jpg_start, 13635},
    {"avatar/blond_hazel/frost-snow", _binary_a_d4bb92b37b286b7b3ee0d3ec3b2632b2ccdaf8d4a0cdeee55e64665abbd5200e_jpg_start, 13461},
    {"avatar/brown_brown/neutral", _binary_a_9140d3b5f96f7d89d4dd8e35618e5242ffd663f96a9a61b6ca2d644ce6da62c3_jpg_start, 13614},
    {"avatar/blond_hazel/neutral", _binary_a_52f44be5123809e3f5732f7d87718d898bbb6418f6edb89d53eeb87955a9b8b4_jpg_start, 13788},
    {"avatar/brown_brown/hot-sunhat", _binary_a_db0cf2dc5c7f45c449c46caee8e8b238a7a7a62bdc38b82e9c5de0a1d1d1b79c_jpg_start, 14351},
    {"avatar/blond_hazel/hot-sunhat", _binary_a_771f490cb1c5d9762ca0c83bbec5f8a19e5e2da348b7a5c2bd4b6032c8cb7038_jpg_start, 14353},
    {"weather/clear-night", _binary_a_557b0645b67c817c2a95e6a212aa38fdbf1cf57c6f9b0550e995aa638aeeb4b4_jpg_start, 13964},
    {"weather/cloudy", _binary_a_86d6bded2044c8aa0c7f8183f4b213f157336b84ce51d3184cfc380b5d75ff3b_jpg_start, 14843},
    {"weather/exceptional", _binary_a_89eac31281e5084aa5c771a952e14b31406622687e72300f130039e408eac335_jpg_start, 20613},
    {"weather/fog", _binary_a_d69cbacea29f5b9917f60fd8d2078b4ba5da85755c88c82e0ad489dd899709bf_jpg_start, 13883},
    {"weather/hail", _binary_a_0d53746f1f35d7fb696963e186d37daf3f1a469eea008afd74cb3e04c48a847a_jpg_start, 42664},
    {"weather/lightning-rainy", _binary_a_3c2ae47017c0c9568b83bb14b2adbe3ba4c1f94e43946b62e23115d9fa16e8bb_jpg_start, 28058},
    {"weather/lightning", _binary_a_53e376b19b21436ae0c1d1e53324c89ee0368b9e2dee8c88c062ab065f6c2e13_jpg_start, 20080},
    {"weather/partlycloudy", _binary_a_91b6b93a61996d3c44eca47178d1960586577bf0bd65418b66de24e872dd0ef1_jpg_start, 17905},
    {"weather/pouring", _binary_a_6157d31c358ab9ce6f187163b4b5d3ba3c23aa751c0ef58917d97a77773a68a9_jpg_start, 19912},
    {"weather/rainy", _binary_a_cc7f857ca5cacf68ded3b8f1dfc36be9af5b22c4a0b4603cda84af8f43972133_jpg_start, 32629},
    {"weather/snowy-rainy", _binary_a_995b257794d77374b3487eb99db66aaeaaed865b4fa9b941e421663998560678_jpg_start, 36142},
    {"weather/snowy", _binary_a_bd8745289e1da57e4aad3c5dadb1fc31c616f7d8c4c39af42cd46fd3bf38891d_jpg_start, 27635},
    {"weather/sunny", _binary_a_7cf482cef766d06ae57125c5abfa3e702ff297fd03bfbd71524d3cf94d623a63_jpg_start, 15740},
    {"weather/windy-variant", _binary_a_2a40e7d0492e39b854886a057c8d1f5d1e915fdcebe7f55d90e6931275407146_jpg_start, 26887},
    {"weather/windy", _binary_a_14f0a0ce495464abb26f74aa759d7c705697667539acd19602f3d47b08899f0b_jpg_start, 30484},
};
